development:
  adapter: postgresql
  database: dont_panic_dev
  host: localhost

test:
  adapter: postgresql
  database: dont_panic_test
  host: localhost

development:
  adapter: postgresql
  database: dont_panic_prod
  host: localhost
